dbuilder-namespace-mapping:
  registry.hub.docker.com: seznam

packages:
  debian:
    templates:
      - {file: apt_based.dockerfile, tags: [squeeze, 6, wheezy, 7, jessie, jessie-backports, 8, latest]}

  ubuntu:
    templates:
      - {file: apt_based.dockerfile, tags: ['12.04', '14.04', '15.04', '15.10']}
