dbuilder-namespace-mapping:
  docker.io: seznam

packages:
  debian:
    templates:
      - {file: apt_based.dockerfile, tags: [wheezy, 7, jessie, jessie-backports, 8, latest]}

  ubuntu:
    templates:
      - {file: apt_based.dockerfile, tags: ['12.04', '14.04', '15.04', '15.10']}
